apiVersion: v1
kind: Service
metadata:
  name: fiap-pedidos-api-service
  namespace: fiap-pedidos-api

spec:
  type: LoadBalancer
  selector:
    app: fiap-pedidos-api-deployment
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002